var store = new Vuex.Store({
  mutations,
  getters,
  state: {
    round: 0,
    stage: 0,
    viewGrid: null,
    cities: {
      '3-11': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '3-14': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '4-16': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '6-13': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '7-16': {'state': 4, 'army': 50, 'morale': 100, 'hero': 30, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3},
      '2-20': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '4-19': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '3-22': {'state': 3, 'army': 50, 'morale': 100, 'hero': 20, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3},
      '2-25': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '3-28': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '8-4': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '4-8': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '12-3': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '15-4': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '10-7': {'state': 7, 'army': 50, 'morale': 100, 'hero': 60, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3},
      '6-10': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '8-12': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '9-17': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '9-14': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '11-18': {'state': 6, 'army': 50, 'morale': 100, 'hero': 50, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3},
      '6-20': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '7-22': {'state': 1, 'army': 50, 'morale': 100, 'hero': 0, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3},
      '9-20': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '9-23': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '7-26': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '9-10': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '11-11': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '13-14': {'state': 5, 'army': 50, 'morale': 100, 'hero': 40, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3},
      '13-17': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '11-15': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '14-9': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '16-13': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '15-19': {'state': 2, 'army': 50, 'morale': 100, 'hero': 10, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3},
      '12-22': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0},
      '15-25': {'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0}
    }
  }
});