var store = new Vuex.Store({
  mutations,
  getters,
  state: {
    round: 0,
    stage: 0,
    active: 0,
    rank: [1, 2, 6, 7, 4, 3, 5],
    player: 1,
    history: ['第一回合:'],
    activeGrid: null,
    activeInfo: null,
    attackFrom: null,
    attackTo: null,
    holder: null,
    grids: {
      '1-1': {'type': null}, '1-2': {'type': null}, '1-3': {'type': null}, '1-4': {'type': null}, '1-5': {'type': null},
      '1-6': {'type': null}, '1-7': {'type': null}, '1-8': {'type': null}, '1-9': {'type': null}, '1-10': {'type': null},
      '1-11': {'type': null}, '1-12': {'type': null}, '1-13': {'type': null}, '1-14': {'type': null}, '1-15': {'type': null},
      '1-16': {'type': null}, '1-17': {'type': null}, '1-18': {'type': null}, '1-19': {'type': null}, '1-20': {'type': null},
      '1-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '1-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '1-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '1-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '1-25': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '1-26': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '1-27': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '1-28': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-1': {'type': null}, '2-2': {'type': null}, '2-3': {'type': null}, '2-4': {'type': null}, '2-5': {'type': null},
      '2-6': {'type': null},
      '2-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-12': {'type': null}, '2-13': {'type': null}, '2-14': {'type': null}, '2-15': {'type': null},
      '2-16': {'type': null}, '2-17': {'type': null},
      '2-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-20': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-25': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-26': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-27': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '2-28': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-1': {'type': null}, '3-2': {'type': null}, '3-3': {'type': null}, '3-4': {'type': null}, '3-5': {'type': null},
      '3-6': {'type': null},
      '3-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-11': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-14': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-22': {'type': 'city', 'state': 3, 'army': 50, 'morale': 100, 'hero': 20, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3, 'action': null, 'reminder': 0, 'helper': null},
      '3-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-25': {'type': null}, '3-26': {'type': null},
      '3-27': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '3-28': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-1': {'type': null}, '4-2': {'type': null}, '4-3': {'type': null}, '4-4': {'type': null}, '4-5': {'type': null},
      '4-6': {'type': null},
      '4-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-8': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-16': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-19': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-24': {'type': null}, '4-25': {'type': null}, '4-26': {'type': null},
      '4-27': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '4-28': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-1': {'type': null}, '5-2': {'type': null}, '5-3': {'type': null}, '5-4': {'type': null}, '5-5': {'type': null},
      '5-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '5-22': {'type': null}, '5-23': {'type': null}, '5-24': {'type': null}, '5-25': {'type': null}, '5-26': {'type': null},
      '5-27': {'type': null}, '5-28': {'type': null},
      '6-1': {'type': null}, '6-2': {'type': null}, '6-3': {'type': null}, '6-4': {'type': null},
      '6-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-10': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-13': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-20': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '6-23': {'type': null}, '6-24': {'type': null}, '6-25': {'type': null}, '6-26': {'type': null},
      '6-27': {'type': null}, '6-28': {'type': null},
      '7-1': {'type': null}, '7-2': {'type': null}, '7-3': {'type': null},
      '7-4': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-16': {'type': 'city', 'state': 4, 'army': 50, 'morale': 100, 'hero': 30, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3, 'action': null, 'reminder': 0, 'helper': null},
      '7-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-22': {'type': 'city', 'state': 1, 'army': 50, 'morale': 100, 'hero': 0, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3, 'action': null, 'reminder': 0, 'helper': null},
      '7-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-25': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-26': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '7-27': {'type': null}, '7-28': {'type': null},
      '8-1': {'type': null},
      '8-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-3': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-4': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-12': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-25': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '8-26': {'type': null}, '8-27': {'type': null}, '8-28': {'type': null},
      '9-1': {'type': null},
      '9-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-3': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-4': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-10': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-14': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-17': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-20': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-23': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '9-25': {'type': null}, '9-26': {'type': null}, '9-27': {'type': null}, '9-28': {'type': null},
      '10-1': {'type': null},
      '10-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-3': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-4': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-7': {'type': 'city', 'state': 7, 'army': 50, 'morale': 100, 'hero': 60, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3, 'action': null, 'reminder': 0, 'helper': null},
      '10-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '10-25': {'type': null}, '10-26': {'type': null}, '10-27': {'type': null}, '10-28': {'type': null},
      '11-1': {'type': null},
      '11-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-3': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-4': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-11': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-15': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-18': {'type': 'city', 'state': 6, 'army': 50, 'morale': 100, 'hero': 50, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3, 'action': null, 'reminder': 0, 'helper': null},
      '11-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-25': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '11-26': {'type': null}, '11-27': {'type': null}, '11-28': {'type': null},
      '12-1': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-3': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-4': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-22': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-25': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-26': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '12-27': {'type': null}, '12-28': {'type': null},
      '13-1': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-3': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-4': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-14': {'type': 'city', 'state': 5, 'army': 50, 'morale': 100, 'hero': 40, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3, 'action': null, 'reminder': 0, 'helper': null},
      '13-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-17': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-25': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-26': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-27': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '13-28': {'type': null},
      '14-1': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-3': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-4': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-9': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-25': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-26': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-27': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '14-28': {'type': null},
      '15-1': {'type': null},
      '15-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-3': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-4': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-5': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-6': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-19': {'type': 'city', 'state': 2, 'army': 50, 'morale': 100, 'hero': 10, 'supply': 500, 'treasure': 500, 'build': 3, 'enhance': 3, 'action': null, 'reminder': 0, 'helper': null},
      '15-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-25': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-26': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '15-27': {'type': null}, '15-28': {'type': null},
      '16-1': {'type': null},
      '16-2': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-3': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-4': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-5': {'type': null}, '16-6': {'type': null},
      '16-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-13': {'type': 'city', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'build': 0, 'enhance': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-24': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-25': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-26': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-27': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '16-28': {'type': null},
      '17-1': {'type': null}, '17-2': {'type': null}, '17-3': {'type': null}, '17-4': {'type': null}, '17-5': {'type': null},
      '17-6': {'type': null},
      '17-7': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-8': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-15': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-16': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-17': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-18': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-19': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-20': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-21': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-22': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-23': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '17-24': {'type': null}, '17-25': {'type': null}, '17-26': {'type': null}, '17-27': {'type': null}, '17-28': {'type': null},
      '18-1': {'type': null}, '18-2': {'type': null}, '18-3': {'type': null}, '18-4': {'type': null}, '18-5': {'type': null},
      '18-6': {'type': null}, '18-7': {'type': null}, '18-8': {'type': null},
      '18-9': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '18-10': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '18-11': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '18-12': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '18-13': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '18-14': {'type': 'field', 'state': 0, 'army': 0, 'morale': 0, 'hero': null, 'supply': 0, 'treasure': 0, 'action': null, 'reminder': 0, 'helper': null},
      '18-15': {'type': null}, '18-16': {'type': null}, '18-17': {'type': null}, '18-18': {'type': null}, '18-19': {'type': null},
      '18-20': {'type': null}, '18-21': {'type': null}, '18-22': {'type': null}, '18-23': {'type': null}, '18-24': {'type': null}, 
      '18-25': {'type': null}, '18-26': {'type': null}, '18-27': {'type': null}, '18-28': {'type': null},
    }
  }
});